/*
 * RESOURCE SYSTEM
 *
 */

#pragma once

#include <memory>

#include <map>

#include <string>

#include <vector>


// The hand-rolled HashTable hashed with the case bit masked off and compared
// with stricmp, so "Textures/Foo.bmp" and "textures/foo.bmp" were one key.
// Callers rely on that — GetTexture stores under the name it was given but
// loads through a strlwr'd path — so the ordering has to keep ignoring case.


namespace Neuron
{
  class Shape;
  class BitmapRGBA;
  class TextReader;
  class BinaryReader;
  class SoundStreamDecoder;
  class Resource;
  class FileWriter;

  struct ResourceNameLess
  {
      bool operator()(const std::string& _a, const std::string& _b) const { return stricmp(_a.c_str(), _b.c_str()) < 0; }
  };

  class Resource
  {
    protected:
      unsigned int m_nameSeed;
      // Bitmaps that have been registered with the resource system, so that
      // they can be used as if they had been loaded from disk or the archive.
      // USUALLY USED for AUTOGENERATED bitmaps, so that the resource system
      // can regenerate textures for them when the OpenGL context is destroyed.
      std::map<std::string, std::unique_ptr<BitmapRGBA>, ResourceNameLess> m_bitmaps;

      std::map<std::string, int, ResourceNameLess> m_displayLists;

      std::map<std::string, int, ResourceNameLess> m_textures;
      std::map<std::string, std::unique_ptr<Shape>, ResourceNameLess> m_shapes;

      char* m_modName;

      int WildCmp(const char* _wild, const char* _string);

    public:
      // *** Initialisation/Destruction ***
      Resource();
      ~Resource();

      // *** Bitmaps ***
      void AddBitmap(const char* _name, const BitmapRGBA& _bmp, bool _mipMapping = true);
      const BitmapRGBA* GetBitmap(const char* _name);
      void DeleteBitmap(const char* _name);

      // *** Textures ***
      int GetTexture(const char* _name, bool _mipMapping = true, bool _masked = true);
      bool DoesTextureExist(const char* _name);
      void DeleteTexture(const char* _name);

      // *** Files ***
      TextReader* GetTextReader(const std::string& _filename); // Caller must delete the TextReader when done
      TextReader* GetTextReader(const char* _filename);        // Caller must delete the TextReader when done
      BinaryReader* GetBinaryReader(const char* _filename);    // Caller must delete the BinaryReader when done
      FileWriter* GetFileWriter(const char* _filename, bool _encrypt);

      // *** Shapes ****
      Shape* GetShape(const char* _name);
      // Never produces an animatable shape because the one shape is shared between all people who call this function with the same shape name. If you
      // want an animatable shape, call GetShapeCopy
      Shape* GetShapeCopy(const char* _name, bool _animating);

      // *** Normal resources ***
      SoundStreamDecoder* GetSoundStreamDecoder(const char* _filename); // Caller must delete the decoder when done

      // *** Display lists ***
      int CreateDisplayList(const char* _name);  // Adds _name to the hashtable and calls glGenLists
      int GetDisplayList(const char* _name);     // Returns -1 if _name doesn't exist
      void DeleteDisplayList(const char* _name); // Removes _name from the hashtable and calls glDeleteLists

      void FlushOpenGlState();
      void RegenerateOpenGlState();

      // Returns a unique name that can be used to identify autogenerated resources. It is the caller's
      // responsibility to delete the name later. Use "delete []" NOT "free".
      char* GenerateName();

      // The vector and every string in it belong to the caller. The strings come
      // from ListDirectory, which allocates them with `new char[]` — free them
      // with delete[], never free().
      std::vector<char*>* ListResources(const char* _dir, const char* _filter, bool _longResults = true);
  };

  // Owned by App, which assigns this during startup. Declared here so the layers
  // below Species can reach the subsystem without including App.h — see
  // tasks/layering-inversion.yaml T8.
  extern Resource* g_resource;
} // namespace Neuron
